GET http://ox.local/api/user/current
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzQzNWUwZGNmY2QzNWUyZjg3MTZmMjFiZTU2YjBkZGI2ZWY0MjE5NzMwOWEyNTZhYmFkYWJmYzI4Yjg5M2IyMGMwY2I4ZmRhNDdmNjJiMzgiLCJpYXQiOjE1ODk4NDIzNTQsIm5iZiI6MTU4OTg0MjM1NCwiZXhwIjoxNjIxMzc4MzU0LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.hjS3w9WvwKnPH-B4BnWVbQumtFMFgQrFGgyItadmeifbCjxR2pZJhuTR7juolBa1NR-90EjaORrj7e9JXGzYshvLWWlRp06g6z01hMSvuliWbNZBrtW6fK2Fd8X6QI-cNbzK9H-ozGHQWkzBv1iUDt4hzU-5VjkSUjRisFirhhrG_roMYONri-Sm9QmSBQJuWk12GzBTZGpqoAYNNO3fxV8nYlw2LpQX6i35vohXaAxGe0fUANTNKCAUPtEYB7-P6res6rD1iCDN2f4I6bAE5KOfhEN9_bX0ompZbywTY-APpEeJwYWvpLhTBOz5kcrkKZWn9U_p1zPtawTFULnksGLVcDZ_WI5_Bp6gLVYF8uF53lYH7R4BihqBPU9IKr5w1fM-SUZbWJgCB38jDCchoszhfS7-IFIRam7cx2e5V3fs7TT8i2HiyaOEyLegEDxkRQ3FZ-byigJ9zQ5igmYOeQruOnYeVYHrKuzCmge98ESlySijx90g-DgsSLSI9yNq-IvnDjPFqOcNs5UI0V6nZNu_2Rs2W6y-gze9GFor8zv3VcQfPKUXvgn-amOGM7HCWkweSqf-V_RO2-dIANpFTIT_ZVf_WYiOSfLBjWMjhj6zDvVhKKqVAU-RfdPjFw0ZybaXDwQ7J_uKvawm2h7L1OdgurvuOyw7AZiVHnasdKo

###
