GET http://ox.local/api/scopes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWZlYWQ5OWIwYjU3MTM0MTgxZTA1MGVlZTg2MTZjODcyNjVkMjMwYTVkNjE2MzBhYTJiYzkwZjVmMTY1ODllODc2MWY4OWQyYzI2YmQ1OGQiLCJpYXQiOjE1OTAxMDI5ODcsIm5iZiI6MTU5MDEwMjk4NywiZXhwIjoxNjIxNjM4OTg3LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.lkgCVXpWM-MhBFILUnqm5C25EirIk2L0pgCssOR_lK8m-Ay1nh1HBP21hoCXm-ZAoWW6JuYKTGIVTtMK90Vmr7c--TuT8WTkNzRW0nCiS_ivdv3A7GT1NdI0jkfTMcz31jXotlH48GURuql5df54Xle9i7TivOC-D50KZUaS1AtoZ2UZvboWGetk4J2k5LTxmzpyAYOmS_He1pqap7CeOk5J40ixP2aNRRjTtIl4idGKq9TfsVp3ablDCCFjSDQ094TL9LxhwSsbEtiZvSHZ34Eh-AflJavxmm4E66ZGwf46Xf_cViaIIqi-gGVxwVItQd4PSH_ETJMCnpTFl7hWXLO2mVvnlczaPAg5FcZNayn33eCyw-Cu8XiQxKbnQ2Sfvu6Sany-0gvVXzSfDwVgXvNt0UeD1rIklL1KyCS6Yctzdok8g8Ph3p_AqG4KjBhOtXTgJ6SYbBrhvlnLAUfrNFGMuFQgdh8DlNo9gazwUkbh1LnNPOIbhJ_hJPF2Pok0erDsh0hRnVQpnR6RdW8rZFvI1cuZELGRjMDiOxGsSGt3sdqqDreoDyyqo12RaWyzCrZON0Xj5XaiibjHNbOfhVWL46ly14bGs5cMkUugOW3WczlsGpF1bK7I_QiNQogNaWoOiZXiCSvZYoRDtaBurT5Py27w2XQ8ZZoHdOcRWo0

###
