GET http://ox.local/api/product/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzJmZmEyNzIxYWE0NTQxZWY5MTg2N2IyYWI1YTQ4N2QxMzBhOGQ4MzQyYTI0NWFmMmJmYzcyMmQ0MTM4ZGNhMDRjYTcxMjMwMTcwYzllM2YiLCJpYXQiOjE1OTAyNzk3NDEsIm5iZiI6MTU5MDI3OTc0MSwiZXhwIjoxNjIxODE1NzQxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.BKKg0PqjTj7SJIX1HswZz8J8-CkpkjcFwEfWAQXaDVUP9KRXzMyWSr3PMTA1V6UAi6EPhcewpiDzrOKTIDFwRQjHszaU5cU0B1ExjPnXL8pVpXTfvt5W3O0yf-8M9aL0fRKvGXPcT7Bjx3APYRX_LIEVDf5s09IxsZIolBEcxYejRN_uigBXixunFReE9O83IsyZCzOJ_p8SRJrq4rEwZBtru7p9qfQpap4HKyKDgfS1yrOn-Ofu5KrKdKlfGhRLxc8_sLskTtMLwCTyUnN7u9iHjf6tvOkxZScNFi-nOpdP6BZi1Uq6uuRUInMSQ_xqUIlMHyGGUx6xuZztEQixzCuNx05zM5ERTgAn-iLTI9NTZWz4CIcmSM7hUObFpZ13qeh1h013_sob819TYe4ju4afFhI2h5uoKxT-e6qO0L5sAW_K_7O6P9GzjNe_odQrWqdzj_xg60l8ZddUW-y9UE-NnySvidQZ1BhJXqA_aKV3moI0Nz2Hg3rQELm1dLHA3JG8pOAbtLvvHlTqG9eTDIf3DthHa0VsUS0y5dl46sRRMc-DQyM4hKGCwCQua2Sl_vTw_74nwi_sKqPF8jVJTkfkpifo932_7OJwkKdqfmwbbnR9_la1fiZtH6YMSe7y1O9d14PbdJJ6NiF0loxxz8xyEi3rPR7bT-WKjd4D1g4

###
